### ISSUE TITLE
Write a function to Identify and extract features from ONE exemplar Temperature monitoring device / patient

### ISSUE THREAD

**Issue by wolass** [wolass/WTM2020#3]
1. Convert json to data frame
2. Identyfy when the sensor was on skin 
3. Identify when it lost contact to skin
4. Identify when the patient has a stable temperature
5. Identify timepoints when the temperature was measured with a reference thermometer 
6. Try to identify daily temperature patterns.

**Comment by kristofrog** [comment]
5. chodzi o to żeby porównać wartości w tym samym czasie z tymi 6 z głównego data,frame?

**Comment by wolass** [comment]
tak

**Comment by kristofrog** [comment]
Mało pacjentów ma 6/6 badań temperatury możliwe opcje:
- nie wszyscy mieli 6 badań manualnym, co widziałem już na początku
- więcej niż 5 minut od najbliższych sąsiadów

**Comment by wolass** [comment]
Ok po prostu tak to opisz. Ile miało pomiar i jak bardzo był on różny od
manualnego.

I jedziemy z kolejnymi punktami bo to było najprostsze zadanie z całego
projektu.
