### ISSUE TITLE
mozliwe ze godziny  na serwerze byly wg czasu uniwersalnego Greenwich

### ISSUE THREAD

**Issue by wolass** [wolass/WTM2020#5]
Prawdopodobnie trzeba dodac 2 h do odczytow zapisanych na serwerze aby zgadzaly sie ze odczytani z termometru manualnego

**Comment by kristofrog** [comment]
Jest pare przypadków, że sensora nie było na ciele a był pomiar manualnym w danej godzine lub nie było w danej sekundzie.
Druga opcja pewnie się rozwiąże tym dodaniem 2h, przykład:
12:29:00 vs 12:29:07
Pierwsza, przykład:
27 dnia sensor działal od 11 coś, jeden pomiar manualnym był o 7.28 przez co się go wyklucza z porównania.

**Comment by wolass** [comment]
jak chodzi o te sekundy to nie jestesmy w stanie tego poprawic 12.29 jest ok. pomiar 7 sekund pozniej jest rowniez w  porzadku
