### ISSUE TITLE
Naucz sie poslugiwac paczka lubridate.

### ISSUE THREAD

**Issue by wolass** [wolass/WTM2020#6]
Nie rozumiem co probujesz osiagnac poprzez ten kod 
```
comp$time <- sub("Z", "", comp$time)
comp$time <- sub("T", " ", comp$time)
```

**Comment by kristofrog** [comment]
Termometr zwykły jest z dokładnością do minuty, a te jsony do sekundy. Właśnie chciałem zrobić z daty termometru zwykłego coś jak ymd_hms(), bo mi porównania nie znajdywało. Dzięki za podpowiedź.
